/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_earctrl_Utils_TunnerThread */

#ifndef _Included_com_example_earctrl_Utils_TunnerThread
#define _Included_com_example_earctrl_Utils_TunnerThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_earctrl_Utils_TunnerThread_MIN_PRIORITY
#define com_example_earctrl_Utils_TunnerThread_MIN_PRIORITY 1L
#undef com_example_earctrl_Utils_TunnerThread_NORM_PRIORITY
#define com_example_earctrl_Utils_TunnerThread_NORM_PRIORITY 5L
#undef com_example_earctrl_Utils_TunnerThread_MAX_PRIORITY
#define com_example_earctrl_Utils_TunnerThread_MAX_PRIORITY 10L
/*
 * Class:     com_example_earctrl_Utils_TunnerThread
 * Method:    processSampleData
 * Signature: ([BI)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_earctrl_Utils_TunnerThread_processSampleData
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
