/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_iwhere_NativeCallObject */

#ifndef _Included_io_iwhere_NativeCallObject
#define _Included_io_iwhere_NativeCallObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_iwhere_NativeCallObject
 * Method:    registerAudioFrameObserver
 * Signature: (Lio/iwhere/IAudioFrameListener;)V
 */
JNIEXPORT void JNICALL Java_io_iwhere_NativeCallObject_registerAudioFrameObserver
        (JNIEnv *, jobject, jobject);

/*
 * Class:     io_iwhere_NativeCallObject
 * Method:    unregisterAudioFrameObserver
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_iwhere_NativeCallObject_unregisterAudioFrameObserver
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
